// src/schema.js
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Parse a schema field type like "String!", "[Order]", "BigInt" into structured info.
export function parseType(type) {
  let t = String(type);
  const required = t.endsWith('!');
  t = t.replace(/!/g, '');
  const list = t.startsWith('[') && t.endsWith(']');
  const base = t.replace(/[\[\]]/g, '');
  return { base, list, required };
}

const SQLITE_TYPES = {
  ID: 'TEXT', String: 'TEXT', Int: 'INTEGER', Float: 'REAL', Boolean: 'INTEGER',
  BigInt: 'TEXT', BigDecimal: 'TEXT', JSON: 'TEXT', Timestamp: 'TEXT',
};
const PG_TYPES = {
  ID: 'TEXT', String: 'TEXT', Int: 'BIGINT', Float: 'DOUBLE PRECISION', Boolean: 'BOOLEAN',
  BigInt: 'NUMERIC', BigDecimal: 'NUMERIC', JSON: 'JSONB', Timestamp: 'TIMESTAMPTZ',
};

export function sqlColumnType(base, list, dialect) {
  if (list) return dialect === 'postgres' ? 'JSONB' : 'TEXT'; // lists stored as JSON
  const map = dialect === 'postgres' ? PG_TYPES : SQLITE_TYPES;
  // relations (entity references) store the foreign id as TEXT
  return map[base] || 'TEXT';
}

// Coerce a raw value (often a string from CSV or a query param) into the JS
// representation implied by its declared schema type. Shared by the engine's
// default column->entity mapping and by the store's query filters, so a
// filter like ?active=true matches a Boolean column and ?items=3 an Int.
export function coerceScalar(value, base, list) {
  if (value == null || value === '') return null;
  if (list && typeof value === 'string') { try { return JSON.parse(value); } catch { return value; } }
  switch (base) {
    case 'Int': return Math.trunc(Number(value));
    case 'Float': return Number(value);
    case 'Boolean': return value === true || value === 'true' || value === '1' || value === 't';
    case 'JSON': return typeof value === 'string' ? JSON.parse(value) : value;
    default: return value; // String/ID/BigInt/BigDecimal/Timestamp/relations stay as-is
  }
}

const TS_SCALARS = {
  ID: 'string', String: 'string', Int: 'number', Float: 'number', Boolean: 'boolean',
  BigInt: 'bigint', BigDecimal: 'string', JSON: 'unknown', Timestamp: 'string',
};

// Generate a .d.ts so handlers get typed entities + ctx.store autocomplete.
export function generateTypes(schema, outDir) {
  const lines = ['// AUTO-GENERATED by Indexa. Do not edit.', ''];
  for (const [entity, fields] of Object.entries(schema)) {
    lines.push(`export interface ${entity} {`);
    for (const [field, type] of Object.entries(fields)) {
      const { base, list, required } = parseType(type);
      const ts = TS_SCALARS[base] || 'string'; // relations -> id string
      lines.push(`  ${field}${required ? '' : '?'}: ${ts}${list ? '[]' : ''};`);
    }
    lines.push('}', '');
  }
  const entities = Object.keys(schema);
  lines.push('export interface Store {');
  for (const e of entities) {
    lines.push(`  upsert(entity: '${e}', id: string, data: Partial<${e}>): Promise<void>;`);
  }
  lines.push(`  get<T = any>(entity: ${entities.map((e) => `'${e}'`).join(' | ')}, id: string): Promise<T | null>;`);
  lines.push('}', '');
  lines.push('export interface Context {');
  lines.push('  store: Store;');
  lines.push('  source: string;');
  lines.push('  cursor: string | number;');
  lines.push('  logger: { info(m: string): void; warn(m: string): void; error(m: string): void; debug(m: string): void };');
  lines.push('}', '');
  const file = join(outDir, 'indexa-types.d.ts');
  writeFileSync(file, lines.join('\n'));
  return file;
}
